# GSolve - gravity processing software.
# Copyright (c) 2026 Earth Sciences New Zealand.
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# SPDX-License-Identifier: GPLv3

# Copyright (c) 2025 Earth Sciences New Zealand.

"""Classes and functions to compute normal gravity and gravity corrections."""

from collections.abc import Sequence as Sequence
from dataclasses import dataclass
from typing import Literal

import boule as boule
import numpy as np
import pandas as pd
from numpy.typing import ArrayLike
from scipy.constants import G

from gsolve.core.data import DataFieldSpecification, GSolveParameters, GSolveTable
from gsolve.core.utils import is_list_like, to_1d_ndarray_or_float
from gsolve.sites import GravitySites

__all__ = [
    "GravityCorrectionParameters",
    "GravityCorrections",
    "GravityCorrectionProvider",
    "normal_gravity_at_stn_elevation",
    "normal_gravity_at_ellipsoid",
    "free_air_correction",
    "atmospheric_correction",
    "bouguer_slab_correction",
    "spherical_bouguer_cap_correction",
    "bouguer_slab_curvature_corrected",
]


def normal_gravity_at_stn_elevation(
    longitude: ArrayLike,
    latitude: ArrayLike,
    height_ellipsoidal: ArrayLike,
    ellipsoid: Literal["WGS84", "GRS80"] | boule.Ellipsoid = "GRS80",
    si_units: bool = False,
) -> float | np.ndarray:
    """
    Calculate normal gravity (gamma) of an ellipsoid at the given latitude and height.

    Computes the magnitude of the gradient of the gravity potential
    (gravitational + centrifugal) generated by the ellipsoid at the
    given geodetic latitude and height above the ellipsoid (geometric height) [1]_.

    Assumes that the internal density distribution of the ellipsoid is such that the
    gravity potential is constant at its surface.

    Based on the closed-form expressions by Lakshmanan (1991) [2]_ and corrected by
    Li & Gotze (2001) [3]_, which do not require the free-air correction. Normal gravity is
    calcualted using `Boule <https://www.fatiando.org/boule/latest/index.html>`_
    from the `Fatiando a Terra <https://www.fatiando.org/>`_ project.

    Parameters
    ----------
    longitude : array-like
        The geodetic longitude in decimal degrees.
    latitude : array-like
        The geodetic latitude in decimal degrees.
    height_ellipsoidal : float or array-like
        The ellipsoidal height in meters.
    ellipsoid: 'WGS84', 'GRS80' or boule.Ellipsoid, default 'GRS80'
        The ellipsoid to use for normal gravity calculation.
    si_units: bool, default False
        Return the value in mGal (False, default) or m/s² (True)

    Returns
    -------
    gamma : float or ndarray
        Normal gravity in mGal or m/s².

    References
    ----------
    .. [1] Hofmann-Wellenhof, B., & Moritz, H. (2006). Physical Geodesy (2nd ed.). Vienna: Springer
    .. [2] Lakshmanan, J. (1991). The generalized gravity anomaly: Endoscopic microgravity.
       GEOPHYSICS, 56(5), 712-723. https://doi.org/10.1190/1.1443090
    .. [3] Li, X., & Götze, H. (2001). Ellipsoid, geoid, gravity, geodesy, and geophysics.
       GEOPHYSICS, 66(6), 1660-1668. https://doi.org/10.1190/1.1487109

    """
    height_ellipsoidal = to_1d_ndarray_or_float(height_ellipsoidal)
    if np.any(height_ellipsoidal < 0):
        raise ValueError("heights must be >= 0.0: ")

    if isinstance(ellipsoid, boule.Ellipsoid):
        e = ellipsoid
    elif ellipsoid == "WGS84":
        e = boule.WGS84
    elif ellipsoid == "GRS80":
        e = boule.GRS80
    else:
        raise ValueError(f"Unknown ellipsoid '{ellipsoid}': must be 'WGS84' or 'GRS80'")

    return e.normal_gravity(
        coordinates=(longitude, latitude, height_ellipsoidal), si_units=si_units
    )


def normal_gravity_at_ellipsoid(
    latitude: ArrayLike,
    ellipsoid: Literal["GRS80", "WGS84", "GRS67"] = "GRS80",
    si_units: bool = False,
) -> float | np.ndarray:
    """
    Calculate normal gravity at the ellipsoid surface using the full Somigliana
    formula.

    Parameters
    ----------
    latitude : array-like
        Latitude in decimal degrees.
    ellipsoid : 'GRS80', 'WGS84', or 'GRS67', default 'GRS80'
        The ellipsoid on which to calculate normal gravity.
        The 'GRS67' ellipsoid is obsolete and not recommended for use. It is provided only for use with older
        datasets. 'WGS84' is treated as being identical to 'GRS80' for normal gravity calculations.
    si_units : bool, default False
        If True return normal gravity in m/s², otherwise in mGal (default).

    Returns
    -------
    gamma : ndarray or float
        Normal gravity on the ellipsoid surface.

    Notes
    -----
    GRS80 ellipsoid parameters are taken from Table 2.2 Physical Geodesy 2nd Edition
    or Moritz 1980 https://doi.org/10.1007/s001900050278

    GRS67 ellipsoid parameters are taken from
    https://bgi.obs-mip.fr/wp-content-omp/uploads/sites/46/2017/10/BGI_Normal_gravity_determination.pdf

    References
    ----------
    Heiskanen, W. A., & Moritz, H. (1967). Physical Geodesy. W. H. Freeman and Company
    Moritz, H. (2000). Geodetic Reference System 1980. Journal of Geodesy, 74(1), 128–133.
    https://doi.org/10.1007/s001900050278

    """
    valid_ellipsoids = ("GRS80", "GRS67", "WGS84")

    if ellipsoid in ("GRS80", "WGS84"):
        gamma_e = 978032.67715  # normal gravity at equator
        gamma_p = 983218.63685  # normal gravity at pole
        a = 6378137  # semi major axis
        b = 6356752.3141  # semi minor axis

    elif ellipsoid == "GRS67":
        gamma_e = 978031.84558
        gamma_p = 983217.72792
        a = 6378160
        b = 6356774.5161
    else:
        raise ValueError(
            f"Unknown ellipsoid '{ellipsoid}': must be one of {valid_ellipsoids}"
        )

    lat = np.deg2rad(latitude)
    normal_gravity = (
        (a * gamma_e * np.cos(lat) ** 2) + (b * gamma_p * np.sin(lat) ** 2)
    ) / np.sqrt((a**2 * np.cos(lat) ** 2) + (b**2 * np.sin(lat) ** 2))

    if si_units:
        return normal_gravity * 1e-5
    return normal_gravity


def free_air_correction(
    latitude: ArrayLike,
    height_ellipsoidal: ArrayLike,
    free_air_gradient: float = 0.3087691,
) -> float | np.ndarray:
    r"""
    Calculate the free air correction (FAC) for height above the 'GRS80' ellipsoid.

    This method uses the second-order formula (eqn 5 in Hinze et al.):

    .. math::
        g_{fac} =  -(0.3087691 - 0.0004398 sin^{2}\phi)h + 7.2125E-08 h^{2}

    where :math:`h` is the elevation of the station above the ellipsoid,
    :math:`\phi` is the station latitude, and :math:`g_{fac}` is the gravitational
    effect of the 'free air' in mGal.

    Parameters
    ----------
    latitude : float, array-like
        Latitude of the station in decimal degrees.
    height_ellipsoidal : float, array-like
        Height of the station above the ellipsoid in meters.
    free_air_gradient : float, default 0.3087691
        The free air gradient in mGal/m.

    Returns
    -------
    free_air_correction : ndarray or float
        The gravitational effect of the elevation of the station above the ellipsoid
        in the absence of topographic mass in mGal.

    References
    ----------
    Hinze, W. J., et. al. (2005). New standards for reducing gravity data: The North
      American gravity database, Geophysics, 70(4) 25-32, https://doi.org/10.1190/1.1988183

    """
    height_ellipsoidal = to_1d_ndarray_or_float(height_ellipsoidal)
    free_air_correction = (
        -(free_air_gradient - 0.0004398 * (np.sin(np.radians(latitude))) ** 2)
        * height_ellipsoidal
        + 7.2125e-08 * height_ellipsoidal**2
    )

    return free_air_correction


def atmospheric_correction(
    height_ellipsoidal: ArrayLike,
) -> float | np.ndarray:
    r"""
    Calculate the gravitational effect of the atmospheric mass as a function of
    station elevation.

    The atmospheric correction (eqn 3 in Hinze et al.), is given by :

    .. math::
        g_{atm} = 0.874 - 9.9E-5 h + 3.5625E-9 h^2

    where :math:`h` is the elevation of the station above the ellipsoid and
    :math:`g_{atm}` is the atmospheric correction in mGal.

    For an evaluation of atmospheric correction in New Zealand see Tenzer et al. (2010).

    Parameters
    ----------
    height_ellipsoidal : array or :class:`pandas.DataFrame`
         Station elevation in meters referenced to the ellipsoid.

    Returns
    -------
    atmospheric_correction : array or :class:`pandas.DataFrame`
        The gravitational effect of the atmosphere in mGal.

    References
    ----------
    Hinze, W. J., et al. (2005). New standards for reducing gravity data: The North
      American gravity database, Geophysics, 70(4) 25-32, https://doi.org/10.1190/1.1988183
    Tenzer, R. et al. (2010). Computation of the atmospheric gravity correction in New Zealand,
      New Zealand Journal of Geology and Geophysics, 53(4), pp. 333-340. https://doi.org/10.1080/00288306.2010.510171.
    """
    height_ellipsoidal = to_1d_ndarray_or_float(height_ellipsoidal)
    atmospheric_correction = (
        0.874 - 9.9e-05 * height_ellipsoidal + 3.5625e-09 * height_ellipsoidal**2
    ) * -1

    return atmospheric_correction


def bouguer_slab_correction(
    height_ellipsoidal: ArrayLike,
    density_crust: float = 2670.0,
    density_water: float = 1030.0,
) -> float | np.ndarray:
    r"""Calculate the classic Bouguer correction.

    The Bouguer correction approximates the gravitational effect of topography
    by with the gravity effect at the surface of an infinite horizontal slab of
    constant thickness and density.

    This Bouguer correction :math:`g_{bg}` is given by:

    .. math::

        g_{bg} = 2 \pi G \rho h

    where :math:`G` is the gravitational constant :math:`h` is the thickness of the slab
    (i.e. height) and density of the slab :math:`\rho`.

    Used to remove the gravitational attraction of topography above the
    ellipsoid from the gravity disturbance. The infinite plate approximation is
    adequate for regions with flat topography and observation points close to
    the surface of the Earth.

    In the oceans, subtracting normal gravity from the observed gravity results
    in over correction because the normal Earth has crust where there was water
    in the real Earth. The Bouguer correction for the oceans aims to remove
    this residual effect due to the over correction:

    .. math::

        g_{bg} = 2 \pi G (\rho_w - \rho_c) |h|

    in which :math:`\rho_w` is the density of water and :math:`\rho_c` is the
    density of the crust of the normal Earth. We need to take the absolute
    value of the bathymetry :math:`h` because it is negative and the equation
    requires a thickness value (positive).

    Parameters
    ----------
    height_ellipsoidal : float or array-like
        Station height relative the ellipsoid or reference datum in meters.
        Positive heights are treated as topographic elevation and the Bouguer correction
        will be calculated using ``density_crust``.
        Negative heights are treated as bathymetric depth and the Bouguer correction
        will be calculated using the difference between ``density_water - density_crust``.
    density_crust : float, default 2670.0
        Density of the crust in :math:`kg/m^3`.
        Used as the density of topography on land and the density of the normal
        Earth's crust in the oceans.
    density_water : float, default 1030.0
        Density of water in :math:`kg/m^3`.

    Returns
    -------
    bouguer_slab_correction : float or array-like
        The gravitational effect of topography and residual bathymetry in mGal.

    """
    height_ellipsoidal = to_1d_ndarray_or_float(height_ellipsoidal)
    density = np.where(
        height_ellipsoidal < 0,
        -1 * (density_water - density_crust),
        density_crust,
    )

    bouguer_slab_correction = 2 * np.pi * G * density * height_ellipsoidal * 1e5

    return bouguer_slab_correction


def spherical_bouguer_cap_correction(
    height_ellipsoidal: ArrayLike,
) -> float | np.ndarray:
    r"""
    Calculate the adjustments to the Bouguer slab correction to account for curvature
    of the Earth.

    The spherical cap correction is given by Hinze (2013):

    .. math::
        g_{spher} =  0.001464139 h - 3.533047e-07 h^{2} + 1.002709e-13 h^{3}
        + 3.002407E-18 h^{4}

    where :math:`h` is the elevation of the station above the ellipsoid
    and :math:`g_{spher}` is the gravitational effect in mGal.


    Parameters
    ----------
    height_ellipsoidal : float or array-like
        Station height(s) in meters relative to the ellipsoid.

    Returns
    -------
    spherical_cap_correction : ndarray or float
        The gravitational effect of the spherical cap in mGal.

    Notes
    -----
    This function assumes a fixed spherical cap extent of 166735.0 meters, equivalent
    to 1.5 degrees of arc on a spherical earth.

    See Also
    --------
    bouguer_slab_curvature_corrected : Calculate the full Bouguer correction,
        including spherical cap correction with customizable cap radius.

    References
    ----------
    Hinze WJ, von Frese RRB, Saad AH, (2013). Gravity and Magnetic Exploration:
      Principles, Practices, and Applications. Cambridge University Press.
      https://doi.org/10.1017/CBO9780511843129
    """
    height_ellipsoidal = to_1d_ndarray_or_float(height_ellipsoidal)
    spherical_bouguer_cap_correction = (
        0.001464139 * height_ellipsoidal
        - 3.533047e-07 * height_ellipsoidal**2
        + 1.002709e-13 * height_ellipsoidal**3
        + 3.002407e-18 * height_ellipsoidal**4
    )

    return spherical_bouguer_cap_correction


def bouguer_slab_curvature_corrected(
    height_ellipsoidal: ArrayLike,
    density_water: float,
    density_crust: float,
    cap_extent: float = 166735.0,
    ellipsoid_or_radius: float | str | boule.Ellipsoid = "GRS80",
) -> float | np.ndarray:
    r"""
    Calculate the spherically corrected Bouguer slab at specified heights.

    This is the function implements the analytic expression from LaFehr _[1]

    This is equivalent to Bullard "A" + Bullard "B" corections.
    .. math::

        g_{sbcc} = 2 \pi G \rho(\mu h - \lambda R)

        g_{sbcc} = 2 \pi G \rho[(1 + \mu) h - \lambda R)]

    where :math:`\mu` and :math:`\lambda` are dimensionless constants,
    :math:`h` is the elevation of the station above ellipsoid and
    :math:`R = Ro + h` where :math:`Ro` is the mean elevation of the ellipsoid.

    The spherical cap correction is added to the infinite slab correction.

    Parameters
    ----------
    height_ellipsoidal : array or :class:`pandas.DataFrame`
        Station height in meters referenced to the ellipsoid.
    density_crust : float
        Density of the crust in :math:`kg/m^3`.
        Used as the density of topography on land and the density of the normal
        Earth's crust in the oceans.
    density_water : float
        Density of water in :math:`kg/m^3`.
    cap_extent : float, default 166735.0
        The width of the cap correction in m. The default value corresponds to
        the Hayford-Bowie 'Zone O' distance, equivalent to 1.5 degrees of arc
        on a spherical earth.
    ellipsoid_or_radius: float | str | boule.Ellipsoid, default 'GRS80'
        Ellipsoid radius in meters, the name of the ellipsoid, or a
        boule.Ellipsoid object. Various ellipsoids are available
        from "Boule" package.

    Returns
    -------
    sb_cap_corr, sb_corr: float or ndarray
        The spherical Bouguer cap correction and spherical Bouguer correction
        in mGal.

    References
    ----------
    ..[1] LaFehr, T. R. (1991). Standardization in gravity reduction,
      Geophysics 56, 1170-1178. https://doi.org/10.1190/1.1443137.
    """
    height_ellipsoidal = to_1d_ndarray_or_float(height_ellipsoidal)
    density = np.where(
        height_ellipsoidal < 0,
        -1 * (density_water - density_crust),
        density_crust,
    )
    Ro: float
    if isinstance(ellipsoid_or_radius, str):
        _er = getattr(boule, ellipsoid_or_radius, None)
        if isinstance(_er, boule.Ellipsoid):
            Ro = float(_er.mean_radius)
        else:
            raise ValueError(
                f"Unknown ellipsoid '{ellipsoid_or_radius}': must be 'WGS84' or 'GRS80'"
            )

    elif isinstance(ellipsoid_or_radius, boule.Ellipsoid):
        Ro = float(ellipsoid_or_radius.mean_radius)
    else:
        Ro = float(ellipsoid_or_radius)

    # Below are the components of the constants mu and lamda

    R = Ro + height_ellipsoidal
    eta = height_ellipsoidal / R
    alpha = cap_extent / Ro
    d = 3 * np.cos(alpha) ** 2 - 2
    f = np.cos(alpha)
    k = np.sin(alpha) ** 2
    p = -6 * np.cos(alpha) ** 2 * np.sin(alpha / 2) + 4 * np.sin(alpha / 2) ** 3
    delta = Ro / R
    m = -3 * k * f
    n = 2 * (np.sin(alpha / 2) - np.sin(alpha / 2) ** 2)
    # constant mu
    mu = (1 / 3) * eta**2 - eta
    # constant lamda
    lamda = (1 / 3) * (
        (d + f * delta + delta**2) * ((f - delta) ** 2 + k) ** 0.5
        + p
        + m * np.log(n / (f - delta + ((f - delta) ** 2 + k) ** 0.5))
    )

    bouguer_slab_curvature_corrected = (
        1e5 * 2 * np.pi * G * density * ((1 + mu) * height_ellipsoidal - lamda * R)
    )
    return bouguer_slab_curvature_corrected


@dataclass
class GravityCorrectionParameters(GSolveParameters):
    """Class to store parameters for normal gravity and anomally calculations.

    Parameters
    ----------
    ellipsoid : "WGS84" or "GRS80" (default)
        The reference ellipsoid used in normal gravity
    density_crust: float, default = 2670.0
        Density of crust in Mg.m**-3
    density_water: float, default = 1030.0
        Density of water in Mg.m**-3
    spherical_cap_radius: float, defult = 166735.0
        The radius in km of the circular cap correction.  The default
        166735.0 km is equivalent to 1.5 degrees of arc for a spherical earth.
    use_curvature_corrected: bool, default True
        Specify the type of Bouguer correction to compute and use in subsequent
        anomaly calculations. If True, bouguer corrections are curvature corrected.
        If False, bouguer corrections are for an infinite horizotal slab.
    use_atmospheric_correction: bool, default True
        Whether to include atmospheric correction in gravity corrections and
        subsequent anomaly calculations.
    free_air_gradient : float, default 0.3087691
        The free air gradient in mGal/m.
    """

    ellipsoid: str = "GRS80"
    density_crust: float = 2670.0
    density_water: float = 1030.0
    spherical_cap_radius: float = 166735.0
    use_curvature_corrected: bool = True
    use_atmospheric_correction: bool = True
    free_air_gradient: float = 0.3087691

    def bouguer_correction_fields(self) -> list[str]:
        """Return tuple of names of correction methods required for
        specified Bouguer method."""
        bc_fields: list[str] = ["normal_gravity_at_ellipsoid", "free_air_correction"]
        if self.use_atmospheric_correction:
            bc_fields.append("atmospheric_correction")
        bc_fields.append(self.bouguer_correction_type())

        return bc_fields

    def bouguer_correction_type(self) -> str:
        """Return the name specified of Bouguer correction method."""
        if self.use_curvature_corrected:
            return "bouguer_slab_curvature_corrected"
        else:
            return "bouguer_slab_correction"


class GravityCorrections(GSolveTable):
    """Class to store gravity corrections and correction parameters.

    Objects of this class are are not intended to be created directly. They are
    generated by calling ``GravityCorrectionProvider.compute()``.

    Parameters
    ----------
    params : GravityCorrectionParameters or None
        Object defining parameters used in computing gravity corrections. If None,
        a default GravityCorrectionParameters object is created.
    site_id : array-like
        Array of unique site identifiers.
    **kwargs : dict
        Keyword arguments providing correction values. The keyword names should
        correspond to known correction types. Call ``GravityCorrections.known_fields()``
        to get a list of valid correction types.

    Attributes
    ----------
    data : pandas.DataFrame
        DataFrame containing gravity corrections, indexed by site_id.
    params : GravityCorrectionParameters
        Parameters used to compute the gravity corrections.
    """

    _known_fields = {
        "site_id": DataFieldSpecification("site_id", str, required=True),
        "longitude": DataFieldSpecification("longitude", float, required=False),
        "latitude": DataFieldSpecification("latitude", float, required=False),
        "height_ellipsoidal": DataFieldSpecification(
            "height_ellipsoidal", float, required=False, legacy_name="height"
        ),
        "normal_gravity_at_stn_elevation": DataFieldSpecification(
            "normal_gravity_at_stn_elevation", float, required=False, default=np.nan
        ),
        "normal_gravity_at_ellipsoid": DataFieldSpecification(
            "normal_gravity_at_ellipsoid", float, required=False, default=np.nan
        ),
        "free_air_correction": DataFieldSpecification(
            "free_air_correction", float, required=False, default=np.nan
        ),
        "bouguer_slab_correction": DataFieldSpecification(
            "bouguer_slab_correction", float, required=False, default=np.nan
        ),
        "bouguer_slab_curvature_corrected": DataFieldSpecification(
            "bouguer_slab_curvature_corrected", float, required=False, default=np.nan
        ),
        "atmospheric_correction": DataFieldSpecification(
            "atmospheric_correction", float, required=False, default=np.nan
        ),
    }

    def __init__(
        self,
        params: GravityCorrectionParameters | None,
        site_id: ArrayLike,
        **kwargs,
    ) -> None:
        self.params = (
            params.copy() if params is not None else GravityCorrectionParameters()
        )

        sids = np.atleast_1d(site_id)
        if len(sids.shape) != 1:
            raise ValueError(f"site_id must be a 1D array, not {len(sids.shape)}D")

        if sids.shape[0] == 0:
            raise ValueError("site_id must not be empty")

        self.data = pd.DataFrame(index=pd.Index(sids, name="site_id"), data=None)

        for k, v in kwargs.items():
            if k in self._known_fields:
                self.set_column(k, v)
            else:
                raise ValueError(f"Unknown correction type '{k}'")

    def __repr__(self) -> str:
        cols = ",".join(self.data.columns.to_list())
        return (
            f"{type(self).__name__}(n_sites={self.data.shape[0]}, corrections={cols})"
        )


class GravityCorrectionProvider:
    """
    Class to calculate normal gravity and various gravity corrections.

    Parameters
    ----------
    params : GravityCorrectionParameters or None
        Object defining parameters used in computing gravity corrections.
        If None, then a GravityCorrectionParameters object will be
        created using default values.
    kwargs : dict
        Additional keyword arguments used to override parameters in the
        supplied GravityCorrectionParameters object ``params``. If ``params`` is None,
        then kwargs are used to override default parameter values.

    Attributes
    ----------
    params : GravityCorrectionParameters
        Parameters used to compute the gravity corrections.
    """

    def __init__(
        self, params: None | GravityCorrectionParameters = None, **kwargs
    ) -> None:
        self.params: GravityCorrectionParameters
        if params is None:
            self.params = GravityCorrectionParameters(**kwargs)
        elif isinstance(params, GravityCorrectionParameters):
            self.params = params
            for k, v in kwargs:
                setattr(self.params, k, v)
        else:
            raise TypeError(
                "params must be None or a GravityCorrectionParameters object, "
                f"not '{type(params)}'"
            )

    def __repr__(self) -> str:
        return f"{type(self).__name__}({self.params.__param_str__()})"

    @classmethod
    def available_corrections(cls) -> tuple[str, ...]:
        """Return tuple of available gravity correction methods"""
        return (
            "normal_gravity_at_stn_elevation",
            "normal_gravity_at_ellipsoid",
            "free_air_correction",
            "atmospheric_correction",
            "bouguer_slab_correction",
            "bouguer_slab_curvature_corrected",
        )

    def compute(
        self,
        sites: GravitySites | pd.DataFrame,
        corrections: str | Sequence[str] | None = None,
        column_names: dict[str, str] | None = None,
        include_coords: bool = False,
    ) -> GravityCorrections:
        """Compute gravity corrections at sites.

        Parameters
        ----------
        sites : GravitySites | DataFrame
            An object providing site longitude, latitude and ellipsoidal height, and indexed
            by ``'site_id'``. If `sites` is a DataFrame, it is expected to have columns named
            ``'longitude'``, ``'latitude'`` and ``'height_ellipsoidal'``, unless alternative columns are
            specified using the `column_names` argument.
        corrections : str | Sequence[str], optional
            An array or string of corrections to compute.  By default compute all
            corrections required for generating a Bouguer anomaly as specified in
            ``self.params``.
        column_names : dict[str, str] | None, optional
            A dictionary mapping expected columns ``longitude``, ``latitude`` and ``height_ellipsoidal``
            to alternative column names. E.g. ``{'longitude': 'lon', 'latitude': 'lat', 'height_ellipsoidal': 'height'}``.
        include_coords : bool, default False
            If True, include site latitude and height in output.

        Returns
        -------
        GravityCorrections
            Object containing computed gravity corrections and the correction parameters.

        """
        _cols = {
            "longitude": "longitude",
            "latitude": "latitude",
            "height_ellipsoidal": "height_ellipsoidal",
        }
        if column_names is not None:
            _cols.update(column_names)

        if isinstance(sites, GravitySites):
            sites_df = sites.data
        elif isinstance(sites, pd.DataFrame):
            sites_df = sites
        else:
            raise TypeError(
                "argument 'sites' must be a Dataframe or GravitySites object, not "
                f"'{type(sites)}'"
            )

        lon = sites_df[_cols["longitude"]].to_numpy()
        lat = sites_df[_cols["latitude"]].to_numpy()
        ht = sites_df[_cols["height_ellipsoidal"]].to_numpy()
        idx = sites_df.index.copy()
        _corrs: list[str]
        if corrections is not None:
            if not is_list_like(corrections):
                _corrs = [str(corrections)]
            else:
                _corrs = [str(c) for c in corrections]

            has_bad_corrections = [
                c for c in _corrs if c not in self.available_corrections()
            ]
            if has_bad_corrections:
                raise ValueError(f"Unrecognised corrections: {has_bad_corrections}")
        else:
            _corrs = self.params.bouguer_correction_fields()

        df = pd.DataFrame(
            index=idx,
            data={"longitude": lon, "latitude": lat, "height_ellipsoidal": ht},
        )
        for c in _corrs:
            df[c] = np.nan

        k = "normal_gravity_at_stn_elevation"
        if k in _corrs:
            df[k] = normal_gravity_at_stn_elevation(
                longitude=lon,
                latitude=lat,
                height_ellipsoidal=ht,
                ellipsoid=self.params.ellipsoid,  # type: ignore[arg-type]
            )

        k = "normal_gravity_at_ellipsoid"
        if k in _corrs:
            df[k] = normal_gravity_at_ellipsoid(
                latitude=lat,
                ellipsoid=self.params.ellipsoid,  # type: ignore[arg-type]
            )

        k = "free_air_correction"
        if k in _corrs:
            df[k] = free_air_correction(
                latitude=lat,
                height_ellipsoidal=ht,
                free_air_gradient=self.params.free_air_gradient,
            )

        k = "atmospheric_correction"
        if k in _corrs:
            df[k] = atmospheric_correction(ht)

        k = "bouguer_slab_correction"
        if k in _corrs:
            df[k] = bouguer_slab_correction(
                height_ellipsoidal=ht,
                density_crust=self.params.density_crust,
                density_water=self.params.density_water,
            )

        k = "bouguer_slab_curvature_corrected"
        if k in _corrs:
            df[k] = bouguer_slab_curvature_corrected(
                height_ellipsoidal=ht,
                density_crust=self.params.density_crust,
                density_water=self.params.density_water,
                cap_extent=self.params.spherical_cap_radius,
                ellipsoid_or_radius=self.params.ellipsoid,
            )

        if not include_coords:
            df = df.drop(
                columns=[
                    _cols["longitude"],
                    _cols["latitude"],
                    _cols["height_ellipsoidal"],
                ]
            )
        _df_dict = {str(k): v for k, v in df.to_dict("list").items()}
        return GravityCorrections(params=self.params, site_id=idx, **_df_dict)

    def _configured_bouguer_corrections(self) -> Sequence[str]:
        """Return bouguer corrections based on the current parameters."""
        corrections = ["normal_gravity_at_ellipsoid", "free_air_correction"]
        if self.params.use_atmospheric_correction:
            corrections.append("atmospheric_correction")
        if self.params.use_curvature_corrected:
            corrections.append("bouguer_slab_curvature_corrected")
        else:
            corrections.append("bouguer_slab_correction")
        return corrections

    def bouguer_corrections(
        self, sites: pd.DataFrame | GravitySites
    ) -> GravityCorrections:
        """Calculate corrections required for computing a Bouguer anomaly as defined in
        ``self.params``.

        Parameters
        ----------
        sites : pd.DataFrame | GravitySites
            An object providing site latitude and ellipsoidal height.
            See ``GravityCorrectionProvider.compute()`` for details.

        Returns
        -------
        GravityCorrections
            Object containing Bouguer corrections and the correction parameters.

        """
        return self.compute(
            sites=sites, corrections=self.params.bouguer_correction_fields()
        )

    def free_air_corrections(
        self, sites: pd.DataFrame | GravitySites
    ) -> GravityCorrections:
        """Calculate corrections required for computing a free air anomaly.

        Parameters
        ----------
        sites : pd.DataFrame | GravitySites
            An object providing site latitude and ellipsoidal height.
            See ``GravityCorrectionProvider.compute()`` for details.

        Returns
        -------
        GravityCorrections
            Object containing free air corrections and the correction parameters.
        """
        return self.compute(
            sites=sites,
            corrections=["normal_gravity_at_ellipsoid", "free_air_correction"],
        )
